name: anchor
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.youda.anchor.model
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_anchor?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
server:
  port: 8888



